name: Go

on:
  push:
  schedule:
    - cron: '29 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: 'run main.go'
      run: go run main.go
    
    - name: 'add data' 
      run: git add .
      
    - name: 'push data'
      uses: actions-go/push@7ad7ce209f2a038e7bca929b7a4c92026363f856
      with:
        commit-message: 'update'
        remote: origin
        force: true
        
