name: Go

on:
  push:
  schedule:
    - cron: '59 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: 'run main.go'
      run: go run main.go
    
    - name: 'add data' 
      run: git add --all
      
    - name: 'push data'
      uses: actions-go/push@v1
      with:
        commit-message: 'new data'
        remote: origin
        force: true
        
