name: Go

on:
  schedule:
    - cron: '1 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: 'run main.go'
      run: go run -v ./../main.go
